"""
PDF Export — ReportLab-based export for DoraEngine research results.
"""
from __future__ import annotations

import io
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ──────────────────────────────────────────────────────────────────────
# Colour palette
# ──────────────────────────────────────────────────────────────────────
_BRAND_DARK   = colors.HexColor("#0f0f1a")
_BRAND_PURPLE = colors.HexColor("#7c3aed")
_BRAND_BLUE   = colors.HexColor("#3b82f6")
_BRAND_CYAN   = colors.HexColor("#06b6d4")
_LIGHT_GRAY   = colors.HexColor("#e5e7eb")
_MID_GRAY     = colors.HexColor("#6b7280")
_TEXT_DARK    = colors.HexColor("#111827")
_TEXT_BODY    = colors.HexColor("#374151")


def _build_styles() -> dict:
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "DoraTitle",
            fontSize=22,
            leading=28,
            fontName="Times-Bold",
            textColor=_BRAND_DARK,
            alignment=TA_CENTER,
            spaceAfter=12,
        ),
        "subtitle": ParagraphStyle(
            "DoraSubtitle",
            fontSize=11,
            leading=14,
            fontName="Times-Roman",
            textColor=_MID_GRAY,
            alignment=TA_CENTER,
            spaceAfter=24,
        ),
        "section": ParagraphStyle(
            "DoraSection",
            fontSize=14,
            leading=18,
            fontName="Times-Bold",
            textColor=_BRAND_DARK,
            spaceBefore=18,
            spaceAfter=8,
        ),
        "body": ParagraphStyle(
            "DoraBody",
            fontSize=11,
            leading=16,
            fontName="Times-Roman",
            textColor=_TEXT_BODY,
            alignment=TA_JUSTIFY,
            spaceAfter=8,
        ),
        "source_title": ParagraphStyle(
            "DoraSourceTitle",
            fontSize=11,
            leading=15,
            fontName="Times-Bold",
            textColor=_BRAND_BLUE,
            spaceAfter=2,
        ),
        "source_url": ParagraphStyle(
            "DoraSourceURL",
            fontSize=9,
            leading=12,
            fontName="Times-Italic",
            textColor=_MID_GRAY,
            spaceAfter=6,
        ),
        "step_title": ParagraphStyle(
            "DoraStepTitle",
            fontSize=10,
            leading=14,
            fontName="Times-Bold",
            textColor=_BRAND_CYAN,
            spaceAfter=2,
        ),
        "step_body": ParagraphStyle(
            "DoraStepBody",
            fontSize=10,
            leading=14,
            fontName="Times-Roman",
            textColor=_TEXT_BODY,
            leftIndent=14,
            spaceAfter=4,
        ),
        "confidence": ParagraphStyle(
            "DoraConfidence",
            fontSize=11,
            leading=14,
            fontName="Times-Bold",
            textColor=_BRAND_PURPLE,
        ),
    }
    return styles


def _divider() -> HRFlowable:
    return HRFlowable(
        width="100%", thickness=0.5, color=_LIGHT_GRAY, spaceAfter=8
    )


def generate_pdf(
    query: str,
    answer: str,
    sources: list[dict],
    reasoning_steps: list[dict],
    confidence: float = 0.0,
    timestamp: Optional[str] = None,
) -> bytes:
    """
    Build a polished PDF and return it as bytes.

    Args:
        query:           The original user query.
        answer:          The final answer text.
        sources:         List of dicts with keys: title, url, snippet, domain.
        reasoning_steps: List of dicts with keys: agent, action, detail.
        confidence:      Float 0–1 confidence score.
        timestamp:       ISO timestamp string (defaults to now).

    Returns:
        Raw PDF bytes ready for download.
    """
    buf = io.BytesIO()
    ts = timestamp or datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2.2 * cm,
        rightMargin=2.2 * cm,
        topMargin=2.2 * cm,
        bottomMargin=2.2 * cm,
    )

    s = _build_styles()
    story = []

    # ── Header ─────────────────────────────────────────────────────────
    story.append(Paragraph("Autonomously Researched Document", s["title"]))
    story.append(Paragraph(f"Generated by DoraEngine • {ts}", s["subtitle"]))
    story.append(_divider())

    # ── Query ──────────────────────────────────────────────────────────
    story.append(Paragraph("Research Query", s["section"]))
    story.append(Paragraph(query, s["body"]))
    story.append(Spacer(1, 6))

    # ── Confidence ────────────────────────────────────────────────────
    pct = int(confidence * 100)
    story.append(
        Paragraph(f"Confidence Score: {pct}%", s["confidence"])
    )
    story.append(Spacer(1, 6))
    story.append(_divider())

    # ── Answer ────────────────────────────────────────────────────────
    story.append(Paragraph("Research Findings", s["section"]))
    # Split by paragraphs and add each
    for para in answer.split("\n\n"):
        clean = para.strip().replace("\n", " ")
        if clean:
            story.append(Paragraph(clean, s["body"]))
    story.append(_divider())

    # ── Sources ───────────────────────────────────────────────────────
    story.append(Paragraph("References", s["section"]))
    for i, src in enumerate(sources, 1):
        title = src.get("title") or src.get("url", "Unknown")
        url   = src.get("url", "")
        snip  = src.get("snippet", "")
        
        # Clean title of any markdown/html artifacts
        title = title.replace('<', '&lt;').replace('>', '&gt;')
        url_escaped = url.replace("&", "&amp;")

        story.append(
            Paragraph(f"{i}. {title}", s["source_title"])
        )
        if url:
            # Clickable link in ReportLab
            link_tag = f'<a href="{url_escaped}" color="{_BRAND_BLUE}">{url_escaped}</a>'
            story.append(Paragraph(link_tag, s["source_url"]))
        if snip:
            # Clean snippet
            snip = snip.replace('<', '&lt;').replace('>', '&gt;')
            story.append(Paragraph(snip[:400], s["body"]))
        story.append(Spacer(1, 6))
    story.append(_divider())

    # ── Reasoning Trace ───────────────────────────────────────────────
    story.append(Paragraph("Agent Reasoning Trace", s["section"]))
    for step in reasoning_steps:
        agent  = step.get("agent", "Agent")
        action = step.get("action", "")
        detail = step.get("detail", "")
        story.append(Paragraph(f"▸ {agent}: {action}", s["step_title"]))
        if detail:
            story.append(Paragraph(str(detail)[:400], s["step_body"]))

    story.append(Spacer(1, 12))
    story.append(
        Paragraph(
            "Powered by DoraEngine — Autonomous AI Research Agent",
            s["subtitle"],
        )
    )

    doc.build(story)
    return buf.getvalue()
